apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

configMapGenerator:
- name: cluster-ocp-configmap
  literals:
  - acm-replicas=1 

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated