apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-machineset-dependency
  namespace: default
data:
  replicas: '{{ $n := split "." (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.apiServerURL }}{{ $clustName := (printf $n._1 "-replicas") }}{{ fromConfigMap "default" "cluster-ocp-configmap" $clustName  }}'
  lookup_e: '{{ $n := split "." (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.apiServerURL }}{{ $clustName2 := (printf (trim $n._1) "-replicas") }}{{ "B" }}{{ $n._1 }}{{ "E" }}'