---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: bry-managed
spec:
  clusterConditions:
  - status: 'True'
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: vendor
      operator: In
      values:
      - OpenShift
    - key: name
      operator: In
      values:
      - bry